# FriendlyPix
pod 'Firebase/Auth'
pod 'Firebase/Database'
pod 'Firebase/Storage'
pod 'Firebase/RemoteConfig'
pod 'Firebase/AdMob'
pod 'Firebase/Invites'
pod 'Firebase/Messaging'
pod 'STXDynamicTableView'

platform :ios, '8.0'
target 'FriendlyPix'
